Repository SnailyCAD/snaily-cadv4, pull requests merged in 2022-05, with the labels that each got.

#712 :hammer: chore: general refactor
  package.json
  packages/api/package.json
  packages/api/src/controllers/dispatch/911-calls/Calls911Controller.ts
  packages/api/src/controllers/dispatch/CombinedUnitsController.ts
  packages/client/package.json
  packages/client/src/components/dispatch/911Call/EventsArea.tsx
  packages/client/src/components/dispatch/active-units/MergeUnitModal.tsx
  packages/client/src/components/dispatch/events/EventItem.tsx
  packages/client/src/components/dispatch/events/UpdateEventForm.tsx
  packages/client/src/components/dispatch/map/calls/ActiveMapCalls.tsx
  packages/client/src/components/dispatch/modals/Manage911CallModal.tsx
  packages/client/src/components/leo/ActiveCalls.tsx
  packages/client/src/components/leo/incidents/IncidentEventsArea.tsx
  packages/client/src/components/shared/NotepadModal.tsx
  packages/client/src/components/shared/Table/TableRow.tsx
  packages/client/src/lib/fetch.ts
  packages/client/src/lib/useFetch.ts
  packages/client/src/pages/citizen/index.tsx
  packages/client/src/pages/dispatch/index.tsx
  packages/client/src/pages/ems-fd/index.tsx
  packages/client/src/pages/officer/call-history.tsx
  packages/client/src/pages/officer/index.tsx
  packages/config/package.json
  packages/permissions/package.json
  packages/schemas/package.json
  packages/types/package.json
  packages/utils/package.json
  packages/utils/src/callsign.ts
  yarn.lock
Labels: enhancement, dependencies

#722 :tada: feat: able to specify division template (paired unit template)
  packages/api/prisma/migrations/20220502143247_/migration.sql
  packages/api/prisma/schema.prisma
  packages/api/src/controllers/admin/values/Import.ts
  packages/api/src/controllers/dispatch/CombinedUnitsController.ts
  packages/client/locales/en/values.json
  packages/client/src/components/admin/values/ManageValueModal.tsx
  packages/client/src/lib/admin/values.tsx
  packages/schemas/src/admin/values/import.ts
  packages/types/src/index.ts
  packages/utils/src/callsign.ts
  packages/utils/tests/callsign.test.ts
Labels: enhancement

#723 :tada: feat: active call column
  packages/api/prisma/migrations/20220502160613_/migration.sql
  packages/api/prisma/schema.prisma
  packages/api/src/controllers/admin/manage/AdminManageUnitsController.ts
  packages/api/src/controllers/dispatch/911-calls/Calls911Controller.ts
  packages/api/src/controllers/leo/LeoController.ts
  packages/api/src/lib/calls/assignUnitsToCall.ts
  packages/client/locales/en/leo.json
  packages/client/src/components/dispatch/ActiveDeputies.tsx
  packages/client/src/components/dispatch/ActiveOfficers.tsx
  packages/client/src/components/dispatch/active-units/officers/ActiveCallColumn.tsx
  packages/client/src/components/dispatch/modals/Manage911CallModal.tsx
  packages/types/src/index.ts
Labels: enhancement

#726 :rocket: feat: improved callsign management
  packages/api/prisma/migrations/20220503141835_/migration.sql
  packages/api/prisma/schema.prisma
  packages/api/src/controllers/admin/manage/AdminManageUnitsController.ts
  packages/api/src/controllers/dispatch/CombinedUnitsController.ts
  packages/api/src/controllers/dispatch/StatusController.ts
  packages/api/src/controllers/ems-fd/EmsFdController.ts
  packages/api/src/controllers/leo/LeoController.ts
  packages/api/src/lib/leo/findNextAvailableIncremental.ts
  packages/api/src/lib/leo/validateDuplicateCallsigns.ts
  packages/api/src/utils/findFirstSmallestInArray.ts
  packages/api/tests/smallest-int-in-array.test.ts
  packages/client/locales/en/admin.json
  packages/client/locales/en/common.json
  packages/client/src/components/admin/Sidebar/routes.ts
  packages/client/src/components/admin/manage/units/CallsignsTab.tsx
  packages/client/src/components/admin/manage/units/ManageUnitCallsignModal.tsx
  packages/client/src/components/leo/CallsignPreview.tsx
  packages/client/src/hooks/useGenerateCallsign.ts
  packages/client/src/pages/admin/manage/units/index.tsx
  packages/client/src/types/ModalIds.ts
  packages/permissions/src/defaults/admin.ts
  packages/permissions/src/permissions.ts
  packages/schemas/src/leo.ts
  packages/types/src/index.ts
  packages/utils/src/callsign.ts
Labels: enhancement

#736 :tada: feat: Enable whitelisting & default rank for EMS/FD (WIP)
  packages/api/prisma/migrations/20220505140647_/migration.sql
  packages/api/prisma/schema.prisma
  packages/api/src/controllers/admin/manage/AdminManageUnitsController.ts
  packages/api/src/controllers/admin/values/Import.ts
  packages/api/src/controllers/admin/values/ValuesController.ts
  packages/api/src/controllers/ems-fd/EmsFdController.ts
  packages/api/src/lib/leo/activeOfficer.ts
  packages/api/src/lib/leo/handleWhitelistStatus.ts
  packages/client/locales/en/admin.json
  packages/client/locales/en/leo.json
  packages/client/src/components/admin/manage/units/AlertDeclineOfficerModal.tsx
  packages/client/src/components/admin/manage/units/AllUnitsTab.tsx
  packages/client/src/components/admin/manage/units/DepartmentWhitelistingTab.tsx
  packages/client/src/components/admin/values/manage-modal/DepartmentFields.tsx
  packages/client/src/components/dispatch/ActiveDeputies.tsx
  packages/client/src/components/ems-fd/modals/SelectDeputy.tsx
  packages/client/src/components/leo/UnitDepartmentStatus.tsx
  packages/client/src/components/leo/modals/SelectOfficerModal.tsx
  packages/client/src/lib/utils.ts
  packages/client/src/pages/admin/manage/units/index.tsx
  packages/client/src/pages/ems-fd/my-deputies.tsx
  packages/client/src/pages/officer/my-officers.tsx
  packages/client/tests/utils.test.ts
  packages/types/src/index.ts
Labels: enhancement

#733 🎉 feat: automatic unit off-duty
  packages/api/prisma/migrations/20220505141915_/migration.sql
  packages/api/prisma/schema.prisma
  packages/api/src/controllers/dispatch/DispatchController.ts
  packages/api/src/controllers/dispatch/StatusController.ts
  packages/api/src/controllers/ems-fd/EmsFdController.ts
  packages/api/src/controllers/leo/LeoController.ts
  packages/api/src/lib/ems-fd.ts
  packages/api/src/lib/leo/activeOfficer.ts
  packages/api/src/lib/leo/setInactiveUnitsOffDuty.ts
  packages/api/src/lib/leo/utils.ts
  packages/client/src/components/admin/manage/cad-settings/MiscFeatures.tsx
Labels: enhancement

#737 🎉 feat: Common citizen cards
  packages/api/prisma/migrations/20220506153633_/migration.sql
  packages/api/prisma/schema.prisma
  packages/api/src/controllers/citizen/CitizenController.ts
  packages/api/src/controllers/citizen/LicenseController.ts
  packages/api/src/controllers/citizen/MedicalRecordController.ts
  packages/api/src/controllers/citizen/TruckLogsController.ts
  packages/api/src/controllers/citizen/VehiclesController.ts
  packages/api/src/controllers/citizen/WeaponController.ts
  packages/api/src/lib/citizen/hasCitizenAccess.ts
  packages/api/src/migrations/disabledFeatureToCadFeature.ts
  packages/client/src/components/admin/manage/cad-settings/CADFeaturesTab.tsx
  packages/client/src/hooks/useFeatureEnabled.ts
  packages/client/src/pages/citizen/index.tsx
  packages/types/src/index.ts
Labels: enhancement

#738 :hammer: chore: bump deps
  package.json
  packages/api/package.json
  packages/client/package.json
  packages/config/package.json
  packages/permissions/package.json
  packages/schemas/package.json
  packages/types/package.json
  packages/utils/package.json
  yarn.lock
Labels: dependencies

#742 🚀 support Steam Oauth
  packages/api/prisma/migrations/20220507133405_/migration.sql
  packages/api/prisma/schema.prisma
  packages/api/src/controllers/auth/Discord.ts
  packages/api/src/controllers/auth/Steam.ts
  packages/api/src/middlewares/IsEnabled.ts
  packages/client/locales/en/account.json
  packages/client/locales/en/auth.json
  packages/client/locales/en/common.json
  packages/client/src/components/Dropdown.tsx
  packages/client/src/components/account/ConnectionsTab.tsx
  packages/client/src/components/admin/manage/cad-settings/CADFeaturesTab.tsx
  packages/client/src/components/admin/values/penal-codes/ManagePenalCode.tsx
  packages/client/src/components/dispatch/modals/ManageUnit.tsx
  packages/client/src/components/modal/DescriptionModal/Toolbar.tsx
  packages/client/src/lib/utils.ts
  packages/client/src/pages/account.tsx
  packages/client/src/pages/admin/index.tsx
  packages/client/src/pages/auth/login.tsx
  packages/client/tests/utils.test.ts
  packages/types/src/index.ts
Labels: enhancement

#745 :tada: feat: able to add description field to DL categories
  packages/api/prisma/migrations/20220508135605_/migration.sql
  packages/api/prisma/schema.prisma
  packages/api/src/controllers/admin/values/Import.ts
  packages/client/src/components/admin/values/ManageValueModal.tsx
  packages/client/src/components/citizen/ManageCitizenForm.tsx
  packages/client/src/components/citizen/licenses/LicensesCard.tsx
  packages/client/src/components/citizen/licenses/ManageLicensesModal.tsx
  packages/client/src/components/form/Select.tsx
  packages/client/src/components/form/select/MultiValueContainerDescription.tsx
  packages/client/src/pages/citizen/create.tsx
  packages/schemas/src/admin/values/import.ts
  packages/types/src/index.ts
  packages/utils/src/typeguards.ts
Labels: enhancement

#750 :tada: feat: show active units on the live map
  packages/api/src/controllers/dispatch/DispatchController.ts
  packages/api/src/lib/ems-fd.ts
  packages/api/src/lib/leo/activeOfficer.ts
  packages/client/package.json
  packages/client/src/components/dispatch/map/units/RenderMapPlayers.tsx
  yarn.lock
Labels: enhancement

#752 :tada: feat: more webhook types
  packages/api/prisma/migrations/20220509170215_/migration.sql
  packages/api/prisma/schema.prisma
  packages/api/src/controllers/calls/TowController.ts
  packages/api/src/controllers/record/RecordsController.ts
  packages/client/src/components/admin/manage/cad-settings/DiscordWebhooksTab.tsx
  packages/schemas/src/admin/index.ts
  packages/types/src/index.ts
Labels: enhancement

#754 :tada: feat: show list of active units on map
  packages/client/locales/en/leo.json
  packages/client/src/components/dispatch/active-units/UnitRadioChannelModal.tsx
  packages/client/src/components/dispatch/map/units/ActiveMapUnits.tsx
  packages/client/src/components/dispatch/map/units/PlayerMarker.tsx
  packages/client/src/components/dispatch/map/units/RenderMapPlayers.tsx
  packages/client/src/components/dispatch/map/units/UnitItem.tsx
  packages/client/src/hooks/realtime/useMapPlayers.ts
  packages/client/src/lib/utils.ts
  packages/client/src/types/Map.ts
  packages/client/tests/utils.test.ts
  packages/types/src/index.ts
Labels: enhancement

#755 :hammer: chore: bump deps
  packages/api/package.json
  packages/client/package.json
  packages/permissions/package.json
  packages/schemas/package.json
  packages/types/package.json
  yarn.lock
Labels: dependencies

#758 🎉 feat: auto expire arrest reports (optional feature)
  packages/api/prisma/migrations/20220514053844_/migration.sql
  packages/api/prisma/schema.prisma
  packages/api/src/controllers/admin/manage/cad-settings/CadSettings.ts
  packages/api/src/controllers/leo/JailController.ts
  packages/api/src/lib/leo/utils.ts
  packages/client/src/components/admin/manage/cad-settings/MiscFeatures.tsx
  packages/schemas/src/admin/index.ts
  packages/telemetry/src/index.ts
  packages/types/src/index.ts
Labels: enhancement

#770 :tada: feat: drag and drop to unassign from 911 Call
  packages/client/locales/en/calls.json
  packages/client/src/components/leo/ActiveCalls.tsx
  packages/client/src/components/leo/active-calls/AssignedUnitsColumn.tsx
  packages/client/src/components/shared/dnd/Draggable.tsx
  packages/client/src/state/dispatchState.ts
  packages/client/src/types/DndActions.ts
Labels: enhancement

#772 :tada: feat: able to manage notes (citizens & vehicles)
  packages/api/prisma/migrations/20220515092811_/migration.sql
  packages/api/prisma/schema.prisma
  packages/api/src/controllers/leo/search/NotesController.ts
  packages/api/src/controllers/leo/search/SearchController.ts
  packages/client/locales/en/leo.json
  packages/client/src/components/leo/modals/NameSearchModal/ManageNoteModal.tsx
  packages/client/src/components/leo/modals/NameSearchModal/NameSearchModal.tsx
  packages/client/src/components/leo/modals/NameSearchModal/tabs/NotesTab.tsx
  packages/client/src/components/leo/modals/NameSearchModal/tabs/TabsContainer.tsx
  packages/client/src/components/leo/modals/VehicleSearch/tabs/ResultsTab.tsx
  packages/client/src/components/leo/modals/VehicleSearchModal.tsx
  packages/client/src/types/ModalIds.ts
  packages/schemas/src/leo.ts
  packages/types/src/index.ts
Labels: enhancement

#777 :tada: feat: court entries
  packages/api/prisma/migrations/20220516164823_/migration.sql
  packages/api/prisma/schema.prisma
  packages/api/src/controllers/court/CourtEntryController.ts
  packages/client/locales/en/courthouse.json
  packages/client/src/components/citizen/ManageCitizenForm.tsx
  packages/client/src/components/courthouse/court-entries/CourtEntriesTab.tsx
  packages/client/src/components/courthouse/court-entries/CourtEntryDates.tsx
  packages/client/src/components/courthouse/court-entries/ManageCourtDateModal.tsx
  packages/client/src/components/courthouse/court-entries/ManageCourtEntry.tsx
  packages/client/src/pages/admin/manage/courthouse.tsx
  packages/client/src/pages/courthouse.tsx
  packages/client/src/types/ModalIds.ts
  packages/schemas/src/court.ts
  packages/types/src/index.ts
Labels: enhancement

#779 🎉 feat: courthouse Discord role sync
  packages/api/prisma/migrations/20220516165653_/migration.sql
  packages/api/prisma/schema.prisma
  packages/api/src/controllers/admin/manage/cad-settings/discord/DiscordSettingsController.ts
  packages/api/src/lib/discord/admin.ts
  packages/api/src/lib/discord/auth.ts
  packages/api/src/middlewares/IsAuth.ts
  packages/client/src/components/admin/manage/cad-settings/DiscordRolesTab.tsx
  packages/permissions/src/defaults/admin.ts
  packages/schemas/src/admin/index.ts
  packages/types/src/index.ts
Labels: enhancement

#791 :tada: feat: able to connect departments to rank
  packages/api/prisma/migrations/20220519162327_/migration.sql
  packages/api/prisma/schema.prisma
  packages/api/src/controllers/admin/values/Import.ts
  packages/api/src/controllers/admin/values/ValuesController.ts
  packages/client/src/components/admin/values/ManageValueModal.tsx
  packages/client/src/components/admin/values/manage-modal/StatusValueFields.tsx
  packages/client/src/lib/admin/values.tsx
  packages/client/src/pages/admin/manage/units/[id].tsx
  packages/client/src/pages/admin/values/[path].tsx
  packages/schemas/src/admin/values/import.ts
  packages/types/src/index.ts
Labels: enhancement

#794 :tada: feat: ems/fd deputy logs
  packages/api/prisma/migrations/20220521060146_/migration.sql
  packages/api/prisma/schema.prisma
  packages/api/src/controllers/admin/manage/AdminManageUnitsController.ts
  packages/api/src/controllers/auth/user/UserController.ts
  packages/api/src/controllers/dispatch/StatusController.ts
  packages/api/src/controllers/ems-fd/EmsFdController.ts
  packages/api/src/controllers/leo/LeoController.ts
  packages/api/src/lib/leo/handleStartEndOfficerLog.ts
  packages/client/locales/en/ems-fd.json
  packages/client/locales/en/leo.json
  packages/client/src/components/leo/logs/OfficerLogsTable.tsx
  packages/client/src/pages/admin/manage/units/[id].tsx
  packages/client/src/pages/ems-fd/my-deputy-logs.tsx
  packages/types/src/index.ts
Labels: enhancement

#795 🎉 feat: allow LEO to create citizens (optional)
  packages/api/prisma/migrations/20220521070942_/migration.sql
  packages/api/prisma/schema.prisma
  packages/api/src/controllers/citizen/CitizenController.ts
  packages/api/src/controllers/leo/search/SearchActionsController.ts
  packages/api/src/controllers/leo/search/SearchController.ts
  packages/api/src/lib/citizen.ts
  packages/api/src/middlewares/IsEnabled.ts
  packages/api/src/migrations/disabledFeatureToCadFeature.ts
  packages/client/locales/en/leo.json
  packages/client/src/components/active-bolos/ManageBoloModal.tsx
  packages/client/src/components/admin/manage/cad-settings/CADFeaturesTab.tsx
  packages/client/src/components/form/inputs/InputSuggestions.tsx
  packages/client/src/components/leo/modals/NameSearchModal/CreateCitizenModal.tsx
  packages/client/src/components/leo/modals/NameSearchModal/NameSearchModal.tsx
  packages/client/src/context/ValuesContext.tsx
  packages/client/src/hooks/useFeatureEnabled.ts
  packages/client/src/types/ModalIds.ts
  packages/types/src/index.ts
Labels: enhancement

#796 French Translation
  packages/client/locales/fr_FRA/account.json
  packages/client/locales/fr_FRA/admin.json
  packages/client/locales/fr_FRA/auth.json
  packages/client/locales/fr_FRA/bleeter.json
  packages/client/locales/fr_FRA/business.json
  packages/client/locales/fr_FRA/calls.json
  packages/client/locales/fr_FRA/citizen.json
  packages/client/locales/fr_FRA/common.json
  packages/client/locales/fr_FRA/courthouse.json
  packages/client/locales/fr_FRA/ems-fd.json
  packages/client/locales/fr_FRA/leo.json
  packages/client/locales/fr_FRA/truck-logs.json
  packages/client/locales/fr_FRA/values.json
  packages/client/next.config.js
Labels: good first issue, translation

#798 :hammer: chore: bump deps
  package.json
  packages/api/package.json
  packages/client/package.json
  packages/config/package.json
  packages/permissions/package.json
  packages/schemas/package.json
  packages/types/package.json
  packages/utils/package.json
  yarn.lock
Labels: dependencies

#808 🎉 feat: call types
  packages/api/prisma/migrations/20220526080330_/migration.sql
  packages/api/prisma/schema.prisma
  packages/api/src/controllers/admin/values/Import.ts
  packages/api/src/controllers/admin/values/ValuesController.ts
  packages/api/src/controllers/dispatch/911-calls/Calls911Controller.ts
  packages/api/src/lib/values/utils.ts
  packages/api/src/middlewares/ValidPath.ts
  packages/client/locales/en/calls.json
  packages/client/locales/en/values.json
  packages/client/src/components/admin/Sidebar/routes.ts
  packages/client/src/components/admin/values/ManageValueModal.tsx
  packages/client/src/components/dispatch/modals/Manage911CallModal.tsx
  packages/client/src/context/ValuesContext.tsx
  packages/client/src/lib/admin/values.tsx
  packages/client/src/pages/dispatch/index.tsx
  packages/client/src/pages/officer/index.tsx
  packages/permissions/src/permissions.ts
  packages/schemas/src/admin/values/import.ts
  packages/schemas/src/dispatch/911-calls.ts
  packages/types/src/index.ts
  packages/utils/src/typeguards.ts
Labels: enhancement

#811 :hammer: chore: bump deps
  packages/api/package.json
  packages/client/package.json
  packages/client/src/components/modal/Modal.tsx
  packages/config/package.json
  packages/permissions/package.json
  packages/utils/package.json
  yarn.lock
Labels: dependencies
