Repository SnailyCAD/snaily-cadv4, pull requests merged in 2022-07, with the labels that each got.

#945 api description and example body/schema rework
  packages/api/src/controllers/admin/AdminController.ts
  packages/api/src/controllers/admin/import/ImportCitizensController.ts
  packages/api/src/controllers/admin/import/ImportVehiclesController.ts
  packages/api/src/controllers/admin/import/ImportWeaponsController.ts
  packages/api/src/controllers/admin/manage/AdminManageCitizensController.ts
  packages/api/src/controllers/admin/manage/AdminManageCustomFieldsController.ts
Labels: documentation, enhancement

#946 :rocket: refactor: improve `temp*` state
  packages/client/src/components/active-bolos/ActiveBolos.tsx
  packages/client/src/components/active-bolos/BoloColumn.tsx
  packages/client/src/components/admin/manage/citizens/AllCitizensTab.tsx
  packages/client/src/components/admin/manage/units/AllUnitsTab.tsx
  packages/client/src/components/admin/manage/units/CallsignsTab.tsx
  packages/client/src/components/admin/manage/units/QualificationsTable.tsx
  packages/client/src/components/business/manage/EmployeesTab.tsx
  packages/client/src/components/business/manage/VehiclesTab.tsx
  packages/client/src/components/calls/TowTaxiCallsTable.tsx
  packages/client/src/components/citizen/medical-records/MedicalRecords.tsx
  packages/client/src/components/citizen/vehicles/VehiclesCard.tsx
  packages/client/src/components/citizen/weapons/WeaponsCard.tsx
  packages/client/src/components/courthouse/court-entries/CourtEntriesTab.tsx
  packages/client/src/components/courthouse/court-entries/CourtEntryDates.tsx
  packages/client/src/components/courthouse/courthouse-posts/CourthousePostsTab.tsx
  packages/client/src/components/dispatch/ActiveDeputies.tsx
  packages/client/src/components/dispatch/ActiveOfficers.tsx
  packages/client/src/components/dispatch/active-calls/EventsArea.tsx
  packages/client/src/components/dispatch/active-units/officers/OfficerColumn.tsx
  packages/client/src/components/dispatch/events/EventItem.tsx
  packages/client/src/components/dispatch/events/UpdateEventForm.tsx
  packages/client/src/components/leo/incidents/IncidentEventsArea.tsx
  packages/client/src/components/leo/modals/ManageRecord/seized-items/SeizedItemsTable.tsx
  packages/client/src/components/leo/modals/NameSearchModal/tabs/NotesTab.tsx
  packages/client/src/hooks/shared/useTemporaryItem.ts
  packages/client/src/pages/admin/manage/businesses.tsx
  packages/client/src/pages/admin/manage/custom-fields.tsx
  packages/client/src/pages/admin/values/[path].tsx
  packages/client/src/pages/business/[id]/[employeeId]/index.tsx
  packages/client/src/pages/ems-fd/my-deputies.tsx
  packages/client/src/pages/officer/call-history.tsx
  packages/client/src/pages/officer/impound-lot.tsx
  packages/client/src/pages/officer/incidents.tsx
  packages/client/src/pages/officer/my-officers.tsx
  packages/client/src/pages/officer/supervisor/dl-exams.tsx
  packages/client/src/pages/officer/supervisor/weapon-exams.tsx
  packages/client/src/pages/tow/logs.tsx
  packages/client/src/pages/truck-logs.tsx
Labels: enhancement

#947 :tada: feat: allow admins to delete registered weapons/vehicles
  packages/api/src/controllers/admin/import/ImportVehiclesController.ts
  packages/api/src/controllers/admin/import/ImportWeaponsController.ts
  packages/client/src/pages/admin/import/vehicles.tsx
  packages/client/src/pages/admin/import/weapons.tsx
  packages/permissions/src/permissions.ts
  packages/types/src/api/admin.ts
Labels: enhancement

#949 🎉 feat: active warrants
  packages/api/prisma/migrations/20220704094711_/migration.sql
  packages/api/prisma/schema.prisma
  packages/api/src/controllers/record/RecordsController.ts
  packages/api/src/lib/leo/officerOrDeputyToUnit.ts
  packages/api/src/lib/records/assignToWarrant.ts
  packages/api/src/middlewares/IsEnabled.ts
  packages/api/src/migrations/disabledFeatureToCadFeature.ts
  packages/api/src/services/SocketService.ts
  packages/client/src/components/admin/manage/cad-settings/CADFeaturesTab.tsx
  packages/client/src/components/leo/ModalButtons.tsx
  packages/client/src/components/leo/active-warrants/ActiveWarrants.tsx
  packages/client/src/components/leo/modals/CreateWarrantModal.tsx
  packages/client/src/hooks/auth/useIsRouteFeatureEnabled.ts
  packages/client/src/hooks/realtime/useActiveWarrants.ts
  packages/client/src/hooks/useFeatureEnabled.ts
  packages/client/src/pages/officer/index.tsx
  packages/client/src/state/leoState.ts
  packages/config/src/socket-events.ts
  packages/schemas/src/records.ts
  packages/types/src/api/courthouse.ts
  packages/types/src/index.ts
Labels: enhancement

#786 :tada: feat: Custom permission roles
  packages/api/prisma/migrations/20220705072227_/migration.sql
  packages/api/prisma/schema.prisma
  packages/api/src/controllers/admin/manage/AdminManageCustomRolesController.ts
  packages/api/src/controllers/admin/manage/ManageUsersController.ts
  packages/api/src/controllers/dispatch/911-calls/Calls911Controller.ts
  packages/api/src/controllers/dispatch/StatusController.ts
  packages/api/src/controllers/leo/search/SearchController.ts
  packages/api/src/lib/auth/getSessionUser.ts
  packages/api/src/lib/citizen/hasCitizenAccess.ts
  packages/api/src/lib/discord/admin.ts
  packages/api/src/lib/ems-fd.ts
  packages/api/src/lib/leo/activeOfficer.ts
  packages/api/src/middlewares/UsePermissions.ts
  packages/client/locales/en/admin.json
  packages/client/src/components/admin/Sidebar/routes.ts
  packages/client/src/components/admin/manage/custom-roles/ManageCustomRolesModal.tsx
  packages/client/src/components/admin/manage/users/ManagePermissionsModal.tsx
  packages/client/src/components/admin/manage/users/ManageRolesModal.tsx
  packages/client/src/components/dispatch/map/units/PlayerMarker.tsx
  packages/client/src/components/nav/dropdowns/DispatchDropdown.tsx
  packages/client/src/hooks/usePermission.ts
  packages/client/src/pages/admin/manage/custom-roles.tsx
  packages/client/src/pages/admin/manage/users/[id].tsx
  packages/client/src/types/ModalIds.ts
  packages/permissions/src/defaults/admin.ts
  packages/permissions/src/index.ts
  packages/permissions/src/permissions.ts
  packages/permissions/tests/index.test.ts
  packages/schemas/src/admin/index.ts
  packages/types/src/api/admin.ts
  packages/types/src/index.ts
Labels: enhancement

#971 :tada: feat: vehicle appearance data
  packages/api/prisma/migrations/20220713073123_/migration.sql
  packages/api/prisma/schema.prisma
  packages/api/src/controllers/citizen/VehiclesController.ts
  packages/schemas/src/citizen.ts
Labels: enhancement

#976 :hammer: chore: bump deps
  packages/api/package.json
  packages/client/package.json
  packages/config/package.json
  packages/permissions/package.json
  packages/schemas/package.json
  packages/types/package.json
  packages/utils/package.json
  yarn.lock
Labels: enhancement, dependencies

#977 :tada: feat: ability to create records via 'snaily-cad-api-token'
  packages/api/prisma/migrations/20220715065900_/migration.sql
  packages/api/prisma/schema.prisma
  packages/api/src/controllers/record/RecordsController.ts
  packages/api/src/middlewares/ActiveOfficer.ts
  packages/client/src/components/leo/citizen-logs/ArrestReportsTab.tsx
  packages/client/src/components/leo/modals/NameSearchModal/tabs/RecordsTab.tsx
  packages/client/src/pages/officer/jail.tsx
  packages/types/src/api/admin.ts
  packages/types/src/index.ts
Labels: enhancement

#985 :hammer: chore: bump deps
  package.json
  packages/api/package.json
  packages/client/package.json
  packages/client/src/pages/_app.tsx
  packages/schemas/package.json
  packages/utils/package.json
  yarn.lock
Labels: dependencies

#989 :tada: feat: able to grant users manage cad-settings permissions
  packages/api/src/controllers/admin/manage/cad-settings/CADImagesController.ts
  packages/api/src/controllers/admin/manage/cad-settings/CadSettings.ts
  packages/api/src/controllers/admin/manage/cad-settings/discord/DiscordSettingsController.ts
  packages/api/src/controllers/admin/manage/cad-settings/discord/DiscordWebhooksController.ts
  packages/api/src/controllers/dispatch/911-calls/Calls911Controller.ts
  packages/api/src/controllers/leo/incidents/IncidentController.ts
  packages/api/src/middlewares/auth/getUser.ts
  packages/api/src/middlewares/auth/utils.ts
  packages/client/src/components/admin/Sidebar.tsx
  packages/client/src/components/admin/manage/users/ManagePermissionsModal.tsx
  packages/client/src/context/AuthContext.tsx
  packages/config/package.json
  packages/config/src/routes.ts
  packages/permissions/src/defaults/admin.ts
  packages/permissions/src/permissions.ts
  yarn.lock
Labels: enhancement

#992 :tada: feat: seperate tones (ems-fd/leo)
  packages/api/src/controllers/dispatch/DispatchController.ts
  packages/client/src/components/dispatch/ModalButtons.tsx
  packages/client/src/components/dispatch/modals/TonesModal.tsx
  packages/client/src/components/ems-fd/ModalButtons.tsx
  packages/client/src/components/leo/ModalButtons.tsx
Labels: enhancement

#1000 :tada: feat: delete citizen on dead (optional)
  packages/api/prisma/migrations/20220723075107_/migration.sql
  packages/api/prisma/schema.prisma
  packages/api/src/controllers/ems-fd/EmsFdController.ts
  packages/api/src/migrations/disabledFeatureToCadFeature.ts
  packages/client/src/components/admin/manage/cad-settings/CADFeaturesTab.tsx
  packages/client/src/hooks/useFeatureEnabled.ts
  packages/types/src/index.ts
Labels: enhancement

#1002 :hammer: chore: bump deps
  package.json
  packages/api/package.json
  packages/client/package.json
  packages/config/package.json
  packages/permissions/package.json
  packages/schemas/package.json
  packages/utils/package.json
  yarn.lock
Labels: dependencies

#1003 🚀 Upgrade radix-ui to v1
  packages/client/package.json
  packages/client/src/components/admin/values/import/OptionsDropdown.tsx
  packages/client/src/components/shared/ContextMenu.tsx
  packages/client/src/components/shared/HoverCard.tsx
  yarn.lock
Labels: enhancement, dependencies

#984 :tada: feat: Truncate 911-calls' description (WIP)
  packages/api/prisma/schema.prisma
  packages/client/package.json
  packages/client/src/components/dispatch/active-calls/ActiveCalls.tsx
  packages/client/src/components/dispatch/modals/Manage911CallModal.tsx
  packages/client/src/components/modal/DescriptionModal/Editor.tsx
  packages/client/src/components/modal/DescriptionModal/types.ts
  packages/client/src/components/shared/HoverCard.tsx
  packages/client/src/lib/editor/dataToString.ts
  packages/client/src/lib/editor/isArrayEqual.ts
  packages/client/src/styles/globals.scss
  yarn.lock
Labels: enhancement
