Repository SnailyCAD/snaily-cadv4, pull requests merged in 2023-10, with the labels that each got.

#1813 chore: Update French & English translation
  apps/client/locales/en/citizen.json
  apps/client/locales/en/leo.json
  apps/client/locales/fr-FR/account.json
  apps/client/locales/fr-FR/admin.json
  apps/client/locales/fr-FR/auth.json
  apps/client/locales/fr-FR/bleeter.json
  apps/client/locales/fr-FR/business.json
  apps/client/locales/fr-FR/cad-settings.json
  apps/client/locales/fr-FR/calls.json
  apps/client/locales/fr-FR/citizen.json
  apps/client/locales/fr-FR/common.json
  apps/client/locales/fr-FR/ems-fd.json
  apps/client/locales/fr-FR/error-messages.json
  apps/client/locales/fr-FR/leo.json
  apps/client/locales/fr-FR/values.json
  apps/client/locales/fr-FR/webhooks.json
Labels: 🌐 translation

#1815 chore: bump dependencies
  apps/api/.npm-upgrade.json
  apps/api/package.json
  apps/client/package.json
  apps/client/src/components/admin/values/ManageValueModal.tsx
  apps/client/src/components/shared/nav/changelog-modal.tsx
  apps/client/src/pages/admin/values/[path].tsx
  packages/audit-logger/package.json
  packages/config/package.json
  packages/permissions/package.json
  packages/schemas/package.json
  packages/types/package.json
  packages/ui/package.json
  packages/utils/package.json
  pnpm-lock.yaml
Labels: 🔨 dependencies

#1829 feat: able to transfer vehicle to business
  apps/api/src/controllers/business/BusinessController.ts
  apps/api/src/controllers/citizen/vehicles-controller.ts
  apps/client/locales/en/citizen.json
  apps/client/src/components/citizen/vehicles/modals/transfer-vehicle-modal.tsx
  packages/schemas/src/citizen.ts
Labels: ✨ enhancement

#1830 feat: Other license categories
  apps/api/prisma/migrations/20231006080836_other_license_category/migration.sql
  apps/api/prisma/schema.prisma
  apps/api/src/lib/citizen/licenses/update-citizen-license-categories.ts
  apps/client/locales/en/citizen.json
  apps/client/src/components/citizen/licenses/ManageLicensesFormFields.tsx
  apps/client/src/components/citizen/licenses/licenses-card.tsx
  apps/client/src/components/citizen/licenses/manage-licenses-modal.tsx
  apps/client/src/components/dispatch/active-units/deputies/active-deputies.tsx
  apps/client/src/components/dispatch/active-units/deputies/deputy-column.tsx
  apps/client/src/components/dispatch/active-units/officers/active-officers.tsx
  apps/client/src/components/dispatch/active-units/officers/columns/officer-column.tsx
  packages/schemas/src/admin/values/import.ts
  packages/schemas/src/citizen.ts
  packages/types/src/enums.ts
Labels: ✨ enhancement

#1841 fix: dependabot alrts
  apps/api/package.json
  package.json
  pnpm-lock.yaml
Labels: 🔨 dependencies

#1833 feat: citizen records payments (Optional Feature)
  apps/api/prisma/migrations/20231007073203_citizen_record_payments/migration.sql
  apps/api/prisma/schema.prisma
  apps/api/src/controllers/record/records-controller.ts
  apps/api/src/middlewares/is-enabled.ts
  apps/api/src/migrations/set-default-cad-features.ts
  apps/client/locales/en/cad-settings.json
  apps/client/locales/en/citizen.json
  apps/client/src/components/leo/modals/NameSearchModal/tabs/records-tab.tsx
  apps/client/src/hooks/useFeatureEnabled.ts
  packages/types/src/enums.ts
  packages/utils/src/api-url.ts
Labels: ✨ enhancement

#1844 fix: pending citizen logs
  apps/api/src/controllers/admin/manage/citizens/records-logs-controller.ts
  apps/client/src/components/leo/citizen-logs/pending-citizen-logs-tab.tsx
  apps/client/src/components/leo/modals/manage-record/manage-record-modal.tsx
  apps/client/src/hooks/shared/table/use-async-table.ts
  apps/client/src/pages/officer/supervisor/citizen-logs/index.tsx
  packages/types/src/api/admin.ts
Labels: ✨ enhancement

#1847 chore: update react aria
  .eslintrc
  apps/client/package.json
  apps/client/src/components/auth/api-verification.tsx
  apps/client/src/components/dispatch/modals/tones-modal.tsx
  apps/client/src/components/leo/modals/NameSearchModal/speech-alert.tsx
  apps/client/src/components/modal-buttons/modal-button.tsx
  apps/client/src/components/shared/VersionDisplay.tsx
  apps/client/src/components/shared/image-wrapper.tsx
  apps/client/src/hooks/realtime/use-active-dispatchers.ts
  apps/client/src/hooks/use-invalidate-query.ts
  package.json
  packages/ui/package.json
  packages/ui/src/components/button/button.tsx
  packages/ui/src/components/fields/date-picker-field.tsx
  packages/ui/src/components/inputs/checkbox.tsx
  packages/ui/src/components/inputs/input.tsx
  packages/ui/src/components/inputs/textarea.tsx
  packages/ui/src/components/multi-form/multi-form-step.tsx
  pnpm-lock.yaml
Labels: 🔨 dependencies

#1854 feat: deleteable penal codes
  apps/api/prisma/migrations/20231021140807_deletable_penal_codes/migration.sql
  apps/api/prisma/schema.prisma
  apps/client/locales/en/leo.json
  apps/client/src/components/courthouse/expungement-requests/request-expungement-modal.tsx
  apps/client/src/components/form/select/MultiValueContainerPenalCode.tsx
  apps/client/src/components/leo/ViolationsColumn.tsx
  apps/client/src/components/leo/modals/manage-record/manage-record-modal.tsx
  apps/client/src/components/leo/modals/manage-record/penal-codes-table.tsx
  apps/client/src/components/leo/modals/manage-record/table-item-form.tsx
  packages/types/src/api/admin.ts
  packages/types/src/index.ts
Labels: ✨ enhancement

#1853 feat: server sorting
  apps/api/package.json
  apps/api/src/controllers/admin/manage/cad-settings/cad-settings-controller.ts
  apps/api/src/controllers/admin/manage/manage-businesses-controller.ts
  apps/api/src/controllers/admin/manage/manage-citizens-controller.ts
  apps/api/src/controllers/admin/manage/manage-users-controller.ts
  apps/api/src/controllers/admin/manage/units/department-time-logs-controller.ts
  apps/api/src/controllers/admin/values/values-controller.ts
  apps/api/src/utils/order-by.ts
  apps/client/src/components/admin/manage/cad-settings/general/blacklisted-words-tab.tsx
  apps/client/src/components/admin/manage/citizens/all-citizens-tab.tsx
  apps/client/src/components/admin/manage/units/tabs/callsigns-tab/callsigns-tab.tsx
  apps/client/src/components/admin/manage/units/tabs/department-time-logs/department-time-logs-table.tsx
  apps/client/src/components/admin/manage/users/tabs/all-users-tab.tsx
  apps/client/src/components/citizen/tow/tow-taxi-calls-table.tsx
  apps/client/src/components/shared/table/table.tsx
  apps/client/src/hooks/shared/table/use-async-table.ts
  apps/client/src/hooks/shared/table/use-table-state.ts
  apps/client/src/pages/admin/manage/audit-logs.tsx
  apps/client/src/pages/admin/manage/businesses/[id].tsx
  apps/client/src/pages/admin/manage/businesses/index.tsx
  apps/client/src/pages/admin/values/[path].tsx
  apps/client/src/pages/ems-fd/hospital-services.tsx
  apps/client/src/pages/officer/impound-lot.tsx
  apps/client/src/pages/officer/my-record-reports.tsx
  apps/client/src/pages/pets/index.tsx
  apps/client/src/pages/tow/logs.tsx
  pnpm-lock.yaml
Labels: ✨ enhancement

#1858 feat: call 911 disposition code
  apps/api/prisma/migrations/20231023170026_disposition_code_call/migration.sql
  apps/api/prisma/schema.prisma
  apps/api/src/controllers/admin/values/import-values-controller.ts
  apps/client/locales/en/calls.json
  apps/client/locales/en/values.json
  apps/client/src/components/admin/values/ManageValueModal.tsx
  apps/client/src/components/dispatch/active-calls/modals/manage-911-call-form.tsx
  apps/client/src/components/form/inputs/value-select-field.tsx
  apps/client/src/lib/admin/values/values.tsx
  packages/schemas/src/admin/values/import.ts
Labels: ✨ enhancement

#1860 feat: able to export entire citizen record log
  apps/api/src/controllers/citizen/CitizenController.ts
  apps/api/src/controllers/record/records-controller.ts
  apps/api/src/templates/citizen-criminal-record.ejs
  apps/client/locales/en/leo.json
  apps/client/locales/en/webhooks.json
  apps/client/src/components/leo/modals/NameSearchModal/tabs/records-tab.tsx
  apps/client/src/pages/officer/supervisor/citizen-logs/[citizenId].tsx
Labels: ✨ enhancement
