Repository SnailyCAD/snaily-cadv4, pull requests merged in 2023-08, with the labels that each got.

#1751 feat: vehicle model images
  apps/api/prisma/migrations/20230806071701_vehicle_model_images/migration.sql
  apps/api/prisma/schema.prisma
  apps/api/src/controllers/admin/values/values-controller.ts
  apps/api/src/controllers/citizen/vehicles-controller.ts
  apps/client/locales/en/citizen.json
  apps/client/src/components/admin/values/ManageValueModal.tsx
  apps/client/src/components/admin/values/manage-modal/vehicle-fields.tsx
  apps/client/src/components/citizen/vehicles/modals/register-vehicle-modal.tsx
  apps/client/src/components/citizen/vehicles/vehicles-card.tsx
  apps/client/src/components/leo/modals/VehicleSearch/tabs/ResultsTab.tsx
  apps/client/src/components/leo/modals/VehicleSearchModal.tsx
  apps/client/src/lib/admin/values/values.tsx
Labels: ✨ enhancement

#1758 chore: remove copy-env command
  .gitignore
  apps/api/.env
  apps/api/package.json
  apps/client/.env
  apps/client/package.json
  package.json
  scripts/set-client-port.mjs
  turbo.json
  yarn.lock
Labels: 📖 documentation

#1760 feat: London Studios SmartSigne integration
  apps/client/locales/en/leo.json
  apps/client/src/components/dispatch/map/calls/call-item.tsx
  apps/client/src/components/dispatch/map/calls/render-active-map-calls.tsx
  apps/client/src/components/dispatch/map/map-actions.tsx
  apps/client/src/components/dispatch/map/map.tsx
  apps/client/src/components/dispatch/map/render-map-blips.tsx
  apps/client/src/components/dispatch/map/smart-signs/render-map-smart-signs.tsx
  apps/client/src/components/dispatch/map/smart-signs/smart-sign-marker.tsx
  apps/client/src/components/dispatch/map/smart-signs/use-smart-signs.tsx
  apps/client/src/components/dispatch/map/units/active-map-units.tsx
  apps/client/src/components/dispatch/map/units/player-marker.tsx
  apps/client/src/components/dispatch/map/units/render-map-players.tsx
  apps/client/src/hooks/realtime/use-map-players.tsx
  apps/client/src/hooks/realtime/useActiveDeputies.ts
  apps/client/src/hooks/realtime/useActiveOfficers.ts
  apps/client/src/lib/map/blips.ts
  apps/client/src/state/mapState.ts
  apps/client/src/types/map.ts
  packages/permissions/src/permissions.ts
Labels: 📖 documentation, ✨ enhancement

#1765 feat: able to specify a description on name change/expungement requests
  apps/api/prisma/migrations/20230821091842_comments_on_courthouse_requests/migration.sql
  apps/api/prisma/schema.prisma
  apps/api/src/controllers/court/ExpungementRequestsController.ts
  apps/api/src/controllers/court/NameChangeRequestController.ts
  apps/client/src/components/admin/manage/courthouse/expungement-requests-tab.tsx
  apps/client/src/components/admin/manage/courthouse/name-change-requests-tab.tsx
  apps/client/src/components/courthouse/expungement-requests/expungement-requests-tab.tsx
  apps/client/src/components/courthouse/expungement-requests/request-expungement-modal.tsx
  apps/client/src/components/courthouse/name-change/name-change-requests-tab.tsx
  apps/client/src/components/courthouse/name-change/request-name-change-modal.tsx
  packages/schemas/src/court.ts
Labels: ✨ enhancement

#1767 feat: export records to PDF
  apps/api/package.json
  apps/api/src/controllers/leo/search/SearchController.ts
  apps/api/src/controllers/record/records-controller.ts
  apps/api/src/templates/record.ejs
  apps/client/locales/en/common.json
  apps/client/locales/en/webhooks.json
  apps/client/src/components/leo/modals/NameSearchModal/tabs/records-tab.tsx
  yarn.lock
Labels: ✨ enhancement

#1770 feat(discord): more webhook types
  apps/api/prisma/migrations/20230829143916_more_webhook_types/migration.sql
  apps/api/prisma/schema.prisma
  apps/api/src/controllers/admin/manage/manage-users-controller.ts
  apps/api/src/controllers/admin/manage/units/manage-units-controller.ts
  apps/api/src/controllers/auth/auth-controller.ts
  apps/api/src/controllers/leo/my-officers/upsert-officer.ts
  apps/client/locales/en/cad-settings.json
  apps/client/locales/en/webhooks.json
  apps/client/src/components/admin/manage/cad-settings/discord-webhooks/WebhookSettingsField.tsx
  apps/client/src/components/admin/manage/cad-settings/discord-webhooks/discord-webhooks-tab.tsx
  apps/client/src/components/admin/manage/users/tabs/pending-users-tab.tsx
  packages/schemas/src/admin/index.ts
  packages/types/src/enums.ts
Labels: ✨ enhancement

#1771 chore: migrate to pnpm
  .github/pull_request_template.md
  .github/workflows/chromatic.yml
  .github/workflows/lint.yml
  .github/workflows/test-builds-typecheck.yml
  .gitignore
  .npmrc
  .yarn/releases/yarn-3.6.0.cjs
  .yarnrc.yml
  apps/api/Dockerfile
  apps/api/package.json
  apps/api/src/controllers/admin/admin-controller.ts
  apps/client/Dockerfile
  apps/client/package.json
  package.json
  packages/audit-logger/package.json
  packages/config/package.json
  packages/permissions/package.json
  packages/schemas/package.json
  packages/types/package.json
  packages/ui/package.json
  packages/utils/package.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
  scripts/copy-env.mjs
  yarn.lock
Labels: 📖 documentation, ✨ enhancement, dependencies
